### ISSUE TITLE
Instagraph Freezes

### ISSUE THREAD

**Issue by Kliklink** [turanmahmudov/Instagraph#1]
Instagraph freezes after one second if you start the app. When you have no internet connection on your phone and open the app, it doesn't freeze. I guess it freezes when catching data...

(bq Aquaris E4.5)

**Comment by turanmahmudov** [comment]
@Kliklink I compressed images on new version of Donate. Which version do you use? I will update the app to see if the bug fixed.

**Comment by Kliklink** [comment]
I use the free version right now.

**Comment by Kliklink** [comment]
Hm, just bought the donate version, but after logging in it just freezes, and shows a spinning wheel.

**Comment by Kliklink** [comment]
On the bq M10 tablet, the free version works, but the donate version freezes after login.

**Comment by turanmahmudov** [comment]
@Kliklink I am working on the new version. It will be fixed.

**Comment by Kliklink** [comment]
Awesome, thank you ;)

**Comment by turanmahmudov** [comment]
@Kliklink a new update for Instagraph Donate is in the Store. can you please check it?

**Comment by Kliklink** [comment]
It still freezes. I also tried to remove the app cache and config from the app. This solved the issue on the M10, but version 0.0.5 still freezes on the E4.5

**Comment by turanmahmudov** [comment]
@Kliklink I use bq aquaris e4.5 and it works without freezing. Does the app crashes on launch?

**Comment by Kliklink** [comment]
It doesn't. It worked some time ago, but then the freeze issue appeared. If I open the app without internet connection it doen't freeze. I've tried multiple Instagram accounts. More people seem to have this issue (according to the reviews of the app).

**Comment by Kliklink** [comment]
Version 0.0.7 solved the issue. Thank you! :)
