### ISSUE TITLE
 Inaccessible Account and " checkpoint_required "

### ISSUE THREAD

**Issue by DansLeRuSH** [turanmahmudov/Instagraph#13]
Hello,

Since yesterday, I can't access to my account on Ubuntu Touch. When I launch the application or when I try to log in, I have this message : " checkpoint_required " (please see the screenshot I attached)

![screenshot20161205_142513466](https://cloud.githubusercontent.com/assets/4101919/20919337/87937210-bb9b-11e6-879d-90893bab0eac.png)

Obviously, Instagraph is unusable.

Best regards,
Franck

My device : Meizu Pro 5 / OTA-13 / Instagraph Alpha 0.0.4

**Comment by turanmahmudov** [comment]
Hi @DansLeRuSH , please open http://instagram.com/ with your web browser and verify your account. Then you can use Instagraph again.

**Comment by DansLeRuSH** [comment]
My bad, I don't understand but my account already exists but there's no more pictures in it and I can't access.

Sorry about that but, of course, you can close this issue.

Best regards,
Franck

**Comment by DansLeRuSH** [comment]
PS : It seems that Instagram doesn't like not having my phone number and unofficial apps. I can reactivate my account only if I use an official application and fill in my phone number ... too bad for them.
