### ISSUE TITLE
Please upload Instagraph to OpenStore

### ISSUE THREAD

**Issue by zubozrout** [turanmahmudov/Instagraph#15]
Hello,
I know Canonical deciding to stop working on phones and everything related stroke all of us hard but it seems that despite my initial fears UBports won't be able to handle this there seems to be quite a lot of stuff happening there. A lot of people are interested in the project and it seems to start taking shape.

With that said I wonder if you are interested in continuing Instagraph development and if you will be uploading that to OpenStore. Unfortunately app purchases is one thing that is missing there.

I am a user of your app and I really do enjoy using it. In fact the reason why I started using Instagram is the fact your app existed and I very much liked how it looked - so the first time I used Instagraph was just to enjoy its great design :).

Thank you very much for your reply.

**Comment by turanmahmudov** [comment]
Hello,
I'm working on new features of Instagraph nowadays. It'll be in the OpenStore soon. :)
Thanks

**Comment by zubozrout** [comment]
Hi,
thank you very much for your positive reply :). I am really looking forward to it - it is a great app and perhaps the most appealing of all Ubuntu apps I know of.

**Comment by turanmahmudov** [comment]
https://open.uappexplorer.com/app/instagraph-devs.turan-mahmudov-l

**Comment by nfsprodriver** [comment]
Thanks for upload the app into the OpenStore, but for me it won't open. Can you check this?

**Comment by turanmahmudov** [comment]
I uploaded a new version of the app. Can you update it?

**Comment by nfsprodriver** [comment]
Yep, now it works, thank you! Issue can be closed again 😄

**Comment by turanmahmudov** [comment]
You're welcome :)
