### ISSUE TITLE
OpenStore version number below Ubuntu Store

### ISSUE THREAD

**Issue by nfsprodriver** [turanmahmudov/Instagraph#19]
@turanmahmudov : When searching for updates in the System Settings, version 0.0.4 is shown up, which is older than OpenStore version 0.0.1.x . There are two ways to fix this:
1. Remove Ubuntu Store version
2. Overtake Ubuntu Store version in the OpenStore
Thank you!

**Comment by turanmahmudov** [comment]
@nfsprodriver I removed Ubuntu Store version. Thanks.
