### ISSUE TITLE
Option button 

### ISSUE THREAD

**Issue by Monmien** [turanmahmudov/Instagraph#2]
I can't access to options because there is nothing when we click on the button (arrow at right on the photo).
Maybe he's doesn't work or the action area is too small.
I'm on mx4, 0.0.7 update. 😉

**Comment by turanmahmudov** [comment]
@Monmien Option button only works with your own photo. If you click on Option button on a photo of other user it wouldn't work. Go to your Profile page, click on a photo from grid and click Option button on new launched page. 
I will increase the Mouse Area of that button also.

**Comment by Monmien** [comment]
Ok cool, I will try when I could uploaded a photo with the app 👍
