### ISSUE TITLE
Instagraph not 100% translated in French

### ISSUE THREAD

**Issue by Anne017** [turanmahmudov/Instagraph#20]
Hello,
Instagraph is currenlty not 100% translated in French.
However, I have just made a commit in PO Editor to change that: https://poeditor.com/join/project/wZiqQyM7ZS
Would it be possible to merge this file?
Thank you in advance.

**Comment by turanmahmudov** [comment]
It's done. Thank you for your support. Translations will be included in the next update.

**Comment by nfsprodriver** [comment]
Updated german translation on poeditor.com
