### ISSUE TITLE
Support Ubuntu convergence (Snap)

### ISSUE THREAD

**Issue by Pharaone** [turanmahmudov/Instagraph#3]
Can you add the support for the amd64,i386 and arm64 in instagraph?(you can do a .click, but the sdk will support snap)

**Comment by turanmahmudov** [comment]
@FaraoneLele yes, I will add

**Comment by FaraoneLele** [comment]
To install Instagraph snap:
sudo snap install --edge --devmode instagraph

**Comment by turanmahmudov** [comment]
`snap install --beta instagraph`

**Comment by turanmahmudov** [comment]
`snap install instagraph`
