### ISSUE TITLE
Untranslatable app

### ISSUE THREAD

**Issue by Pharaone** [turanmahmudov/Instagraph#4]
Can you add the possibility to translate instagraph? Thanks for this awesome app😉

**Comment by FaraoneLele** [comment]
I've started the work on Italian translations

**Comment by turanmahmudov** [comment]
@FaraoneLele you can help to translations from here: https://poeditor.com/join/project/wZiqQyM7ZS

**Comment by Kliklink** [comment]
@turanmahmudov Could you please add Dutch to the list, I'll translate it.

**Comment by turanmahmudov** [comment]
@Kliklink I added. Thanks

**Comment by FaraoneLele** [comment]
I've finished Italian. Can you update the translation? Thanks for this app!

**Comment by FaraoneLele** [comment]
I've shared for help on translating (on the translators group in telegram)

**Comment by turanmahmudov** [comment]
@FaraoneLele thanks for your contribution. I updated the translation. :)

**Comment by FaraoneLele** [comment]
I have seen;)

**Comment by Kliklink** [comment]
@turanmahmudov Dutch translation is finished ;)

**Comment by turanmahmudov** [comment]
@Kliklink thanks a lot :) I updated

**Comment by FaraoneLele** [comment]
turan, you'll want to wait until the fix will not be released. in the meantime you could create milestones with bugs to fix and functions to be added. we can wait for the translations, are not on top of the most important things to do, Instagraph is the best app the same;)

**Comment by Kliklink** [comment]
@turanmahmudov Dutch translation has been updated.

**Comment by nfsprodriver** [comment]
Hello, I created a german translation. Would you upload it? Thanks!

**Comment by turanmahmudov** [comment]
@nfsprodriver I will update it :) Thanks

**Comment by nfsprodriver** [comment]
By the way, how do I set the language? Does it happen automatically or do I have to modify the UBUNTU_TRANSLATION_DOMAIN line from the pro files?

**Comment by FaraoneLele** [comment]
@nfsprodriver you have made the translation with poeditor or with a your text editor? If you have used poeditor don't modify anything

**Comment by nfsprodriver** [comment]
Can someone merge the german translation? I can't switch to it manually. It keep english.

**Comment by turanmahmudov** [comment]
@nfsprodriver there are bugs in Ubuntu SDK, so I can't import translations file to the project.

**Comment by nfsprodriver** [comment]
Okay, how do you usually do this in the SDK? Maybe I'm able to?

**Comment by nfsprodriver** [comment]
Just an idea: E.g. Telegram also uses po importing while compilation. Maybe we can use this as preset? I'll check this as early as I can...

**Comment by tomvicik** [comment]
I've just translated 86% of Czech translation. Have I export it and send you or how does it work please? I'm doing this for the first time...

**Comment by nfsprodriver** [comment]
I think we really should focus on the possibility of translations because this issue is very unnecessary and weird. I tried very many things without success. Maybe there are problems with the name policy like "-donate".

**Comment by turanmahmudov** [comment]
@nfsprodriver I am working on Instagraph for new updates. I plan to unpublish "donate" one and continue to update "stable" one weekly. I will fix translation issues soon. Thanks for your participating.

**Comment by nfsprodriver** [comment]
I built latest commit and now translations work!!! That's great!
