### ISSUE TITLE
Logging in to two-factor authentication enabled account

### ISSUE THREAD

**Issue by berkantkz** [turanmahmudov/Instagraph#40]
I had enabled two-factor authentication method for my account. When I enter click on "Log in", I receive a security code that is used to verify it's me. Even though I receive the security code, I cannot see any screen to enter and verify myself.

**Comment by turanmahmudov** [comment]
Unfortunately this feature is not added to Instagraph yet. I will add it soon. Thanks for reporting.

**Comment by turanmahmudov** [comment]
Duplicate of #28

**Comment by berkantkz** [comment]
I had actually taken a look over the issues in order not to duplicate but I couldn't see it somehow..

**Comment by weyderfs** [comment]
Some news about this bug?

**Comment by Markm52** [comment]
Still here on desktop what gives

**Comment by aviwad** [comment]
still bugs out on ubports
