### ISSUE TITLE
The snap is not working

### ISSUE THREAD

**Issue by EPadronU** [turanmahmudov/Instagraph#43]
## Issue

The application doesn't work.

## Description

I get the following message: `/snap/instagraph/70/bin/instagraph: line 13: /snap/instagraph/70/opt/Instagraph/bin/Instagraph: No such file or directory`.

## System information:

```
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 4.9.97-040997-generic
Shell: fish 2.7.1
Resolution: 1366x768
DE: GNOME 
WM: GNOME Shell
```

**Comment by jeremyllawson** [comment]
Getting the same error here as well. Ubuntu MATE 16.04, 4.13.0-39-generic

**Comment by lmore377** [comment]
Same on Ubuntu 18.04

**Comment by turanmahmudov** [comment]
fixed
