### ISSUE TITLE
Viewing a Post doesn't load

### ISSUE THREAD

**Issue by kugiigi** [turanmahmudov/Instagraph#51]
## Steps to Reproduce
1. Go to your profil or someones else's profile page.
2. Select any of the posted photos.

## Expected Results
The post including the photo will be displayed.

## Actual Results
It just shows a blank page.

**Comment by turanmahmudov** [comment]
Hi @kugiigi 
I updated the app in OpenStore. The update fixes the bug.
Thanks.
