### ISSUE TITLE
 Problems on displaying stories

### ISSUE THREAD

**Issue by Gabriele69** [turanmahmudov/Instagraph#52]
**### Steps to Reproduce**
open a story with a tap

**### Expected Results**
the story opens up showing the content

**### Actual Results**
It just shows a blank page.

NOTE: the stories worked before the last updates (I'm on the RC channel 2019-W09 with a BQ E4.5)

**Comment by turanmahmudov** [comment]
Hi @Gabriele69 
I updated the app in OpenStore. The update fixes the bug.
Thanks.
