### ISSUE TITLE
Account information is empty

### ISSUE THREAD

**Issue by SanderKlootwijk** [turanmahmudov/Instagraph#56]
Since a couple of days the account information (name, bio, followers, profile picture) is empty on the account page. The problem persists both on the page of the current user and on pages of other users.

![screenshot20190404_094238613](https://user-images.githubusercontent.com/12654277/55538210-36856e80-56be-11e9-910a-7759502084af.png)
![screenshot20190404_094400843](https://user-images.githubusercontent.com/12654277/55538211-36856e80-56be-11e9-946c-dfdcb420ecd4.png)

**Comment by ItsYanko** [comment]
Still Not fixed 😕

**Comment by turanmahmudov** [comment]
I'll try to send update tomorrow.

**Comment by turanmahmudov** [comment]
Fixed.

**Comment by SanderKlootwijk** [comment]
Awesome! Thank you!

**Comment by ItsYanko** [comment]
@turanmahmudov when will you send an update to the OpenStore?

**Comment by turanmahmudov** [comment]
Tomorrow
